theme: minima
title: projects
header_pages:
  - about.md
  - bash.md
  - doggo.md
  - index.md

author: Venkat Ranganathan
linkedin_username: venkatesh-ranganathan
#social links:
 #- { platform: linkedin,       user_url: "https://www.linkedin.com/in/venkat-ranganathan" }

