theme: minima
title: projects
header_pages:
  - about.md
  - doggo.md


author: Venkat Ranganathan
aboutme: Hi, I'm Venkat. I'm an Electrical Engineering major at Binghamton University, graduating in May, 2024
linkedin_username: venkatesh-ranganathan

