theme: minima
title: projects
header_pages:
  - about.md
  - roadtrips.md
  #- bash.md
  #- doggo.md
  #- index.md

color_theme: auto
katex: true 

#title: My Jekyll Blog                 # Name of website
#avatar: assets/img/avatar.png         # Path of avatar image, to be displayed in the theme's header
#description: My blog posts            # Short description, primarily used by search engines
#favicon: assets/favicon.ico           # Icon displayed in the tab
#color_theme: auto                     # color theme auto, dark or light

author: Venkat Ranganathan
linkedin_username: venkatesh-ranganathan
#social links:
 #- { platform: linkedin,       user_url: "https://www.linkedin.com/in/venkat-ranganathan" }

