theme: minima
title: projects
header_pages:
  - about.md
  - doggo.md
  - linkedin_username: venkatesh-ranganathan
  
author: Venkat Ranganathan
Social_links:
linkedin_username: venkatesh-ranganathan

